Update ADOPTERS.md
confidential-containers/confidential-containers pull request #227
Opened 2024-08-14 02:50 UTC by yanzhichao

2024-08-14 02:55 UTC, Xynnn007 requested changes
Thanks @yanzhichao for this! Please add a sign-off to your commit and some commit message.

2024-08-15 10:28 UTC, ariel-adam approved these changes
Looks good :-)

2024-08-15 12:32 UTC, fitzthum approved these changes
LGTM

2024-08-15 14:06 UTC, dcmiddle approved these changes

2024-08-15 14:06 UTC, merged